import type { ImageSource } from 'expo-image';

// Generated by scripts/build-images.mjs from assets/masters/exercises — do not edit.

export type ExerciseArt = {
  thumb: ImageSource;
  frames: readonly [ImageSource | null, ImageSource | null];
};

export const EXERCISE_ART: Record<string, ExerciseArt> = {
  'Ab_Crunch_Machine': {
    thumb: require('@/assets/exercises/thumb/Ab_Crunch_Machine.webp'),
    frames: [require('@/assets/exercises/detail/Ab_Crunch_Machine_1.webp'), require('@/assets/exercises/detail/Ab_Crunch_Machine_2.webp')],
  },
  'Ab_Roller': {
    thumb: require('@/assets/exercises/thumb/Ab_Roller.webp'),
    frames: [require('@/assets/exercises/detail/Ab_Roller_1.webp'), require('@/assets/exercises/detail/Ab_Roller_2.webp')],
  },
  'Air_Bike': {
    thumb: require('@/assets/exercises/thumb/Air_Bike.webp'),
    frames: [require('@/assets/exercises/detail/Air_Bike_1.webp'), require('@/assets/exercises/detail/Air_Bike_2.webp')],
  },
  'Arnold_Dumbbell_Press': {
    thumb: require('@/assets/exercises/thumb/Arnold_Dumbbell_Press.webp'),
    frames: [require('@/assets/exercises/detail/Arnold_Dumbbell_Press_1.webp'), require('@/assets/exercises/detail/Arnold_Dumbbell_Press_2.webp')],
  },
  'Around_The_Worlds': {
    thumb: require('@/assets/exercises/thumb/Around_The_Worlds.webp'),
    frames: [require('@/assets/exercises/detail/Around_The_Worlds_1.webp'), require('@/assets/exercises/detail/Around_The_Worlds_2.webp')],
  },
  'Band_Assisted_Pull-Up': {
    thumb: require('@/assets/exercises/thumb/Band_Assisted_Pull-Up.webp'),
    frames: [require('@/assets/exercises/detail/Band_Assisted_Pull-Up_1.webp'), require('@/assets/exercises/detail/Band_Assisted_Pull-Up_2.webp')],
  },
  'Barbell_Bench_Press_-_Medium_Grip': {
    thumb: require('@/assets/exercises/thumb/Barbell_Bench_Press_-_Medium_Grip.webp'),
    frames: [require('@/assets/exercises/detail/Barbell_Bench_Press_-_Medium_Grip_1.webp'), require('@/assets/exercises/detail/Barbell_Bench_Press_-_Medium_Grip_2.webp')],
  },
  'Barbell_Curl': {
    thumb: require('@/assets/exercises/thumb/Barbell_Curl.webp'),
    frames: [require('@/assets/exercises/detail/Barbell_Curl_1.webp'), require('@/assets/exercises/detail/Barbell_Curl_2.webp')],
  },
  'Barbell_Deadlift': {
    thumb: require('@/assets/exercises/thumb/Barbell_Deadlift.webp'),
    frames: [require('@/assets/exercises/detail/Barbell_Deadlift_1.webp'), require('@/assets/exercises/detail/Barbell_Deadlift_2.webp')],
  },
  'Barbell_Hack_Squat': {
    thumb: require('@/assets/exercises/thumb/Barbell_Hack_Squat.webp'),
    frames: [require('@/assets/exercises/detail/Barbell_Hack_Squat_1.webp'), null],
  },
  'Barbell_Hip_Thrust': {
    thumb: require('@/assets/exercises/thumb/Barbell_Hip_Thrust.webp'),
    frames: [require('@/assets/exercises/detail/Barbell_Hip_Thrust_1.webp'), require('@/assets/exercises/detail/Barbell_Hip_Thrust_2.webp')],
  },
  'Standing_Biceps_Cable_Curl': {
    thumb: require('@/assets/exercises/thumb/Standing_Biceps_Cable_Curl.webp'),
    frames: [require('@/assets/exercises/detail/Standing_Biceps_Cable_Curl_1.webp'), require('@/assets/exercises/detail/Standing_Biceps_Cable_Curl_2.webp')],
  },
  'Standing_Calf_Raises': {
    thumb: require('@/assets/exercises/thumb/Standing_Calf_Raises.webp'),
    frames: [require('@/assets/exercises/detail/Standing_Calf_Raises_1.webp'), require('@/assets/exercises/detail/Standing_Calf_Raises_2.webp')],
  },
  'Standing_Dumbbell_Calf_Raise': {
    thumb: require('@/assets/exercises/thumb/Standing_Dumbbell_Calf_Raise.webp'),
    frames: [require('@/assets/exercises/detail/Standing_Dumbbell_Calf_Raise_1.webp'), require('@/assets/exercises/detail/Standing_Dumbbell_Calf_Raise_2.webp')],
  },
  'Standing_Dumbbell_Reverse_Curl': {
    thumb: require('@/assets/exercises/thumb/Standing_Dumbbell_Reverse_Curl.webp'),
    frames: [require('@/assets/exercises/detail/Standing_Dumbbell_Reverse_Curl_1.webp'), require('@/assets/exercises/detail/Standing_Dumbbell_Reverse_Curl_2.webp')],
  },
  'Standing_Dumbbell_Triceps_Extension': {
    thumb: require('@/assets/exercises/thumb/Standing_Dumbbell_Triceps_Extension.webp'),
    frames: [require('@/assets/exercises/detail/Standing_Dumbbell_Triceps_Extension_1.webp'), require('@/assets/exercises/detail/Standing_Dumbbell_Triceps_Extension_2.webp')],
  },
  'Standing_Dumbbell_Upright_Row': {
    thumb: require('@/assets/exercises/thumb/Standing_Dumbbell_Upright_Row.webp'),
    frames: [require('@/assets/exercises/detail/Standing_Dumbbell_Upright_Row_1.webp'), require('@/assets/exercises/detail/Standing_Dumbbell_Upright_Row_2.webp')],
  },
  'Standing_Front_Barbell_Raise_Over_Head': {
    thumb: require('@/assets/exercises/thumb/Standing_Front_Barbell_Raise_Over_Head.webp'),
    frames: [require('@/assets/exercises/detail/Standing_Front_Barbell_Raise_Over_Head_1.webp'), require('@/assets/exercises/detail/Standing_Front_Barbell_Raise_Over_Head_2.webp')],
  },
  'Standing_Military_Press': {
    thumb: require('@/assets/exercises/thumb/Standing_Military_Press.webp'),
    frames: [require('@/assets/exercises/detail/Standing_Military_Press_1.webp'), require('@/assets/exercises/detail/Standing_Military_Press_2.webp')],
  },
  'Standing_Overhead_Barbell_Triceps_Extension': {
    thumb: require('@/assets/exercises/thumb/Standing_Overhead_Barbell_Triceps_Extension.webp'),
    frames: [require('@/assets/exercises/detail/Standing_Overhead_Barbell_Triceps_Extension_1.webp'), require('@/assets/exercises/detail/Standing_Overhead_Barbell_Triceps_Extension_2.webp')],
  },
  'Stiff-Legged_Barbell_Deadlift': {
    thumb: require('@/assets/exercises/thumb/Stiff-Legged_Barbell_Deadlift.webp'),
    frames: [require('@/assets/exercises/detail/Stiff-Legged_Barbell_Deadlift_1.webp'), require('@/assets/exercises/detail/Stiff-Legged_Barbell_Deadlift_2.webp')],
  },
  'Stiff-Legged_Dumbbell_Deadlift': {
    thumb: require('@/assets/exercises/thumb/Stiff-Legged_Dumbbell_Deadlift.webp'),
    frames: [require('@/assets/exercises/detail/Stiff-Legged_Dumbbell_Deadlift_1.webp'), require('@/assets/exercises/detail/Stiff-Legged_Dumbbell_Deadlift_2.webp')],
  },
  'Straight-Arm_Dumbbell_Pullover': {
    thumb: require('@/assets/exercises/thumb/Straight-Arm_Dumbbell_Pullover.webp'),
    frames: [require('@/assets/exercises/detail/Straight-Arm_Dumbbell_Pullover_1.webp'), require('@/assets/exercises/detail/Straight-Arm_Dumbbell_Pullover_2.webp')],
  },
  'Straight-Arm_Pulldown': {
    thumb: require('@/assets/exercises/thumb/Straight-Arm_Pulldown.webp'),
    frames: [require('@/assets/exercises/detail/Straight-Arm_Pulldown_1.webp'), require('@/assets/exercises/detail/Straight-Arm_Pulldown_2.webp')],
  },
  'Sumo_Deadlift': {
    thumb: require('@/assets/exercises/thumb/Sumo_Deadlift.webp'),
    frames: [require('@/assets/exercises/detail/Sumo_Deadlift_1.webp'), null],
  },
  'Superman': {
    thumb: require('@/assets/exercises/thumb/Superman.webp'),
    frames: [require('@/assets/exercises/detail/Superman_1.webp'), require('@/assets/exercises/detail/Superman_2.webp')],
  },
  'T-Bar_Row_with_Handle': {
    thumb: require('@/assets/exercises/thumb/T-Bar_Row_with_Handle.webp'),
    frames: [require('@/assets/exercises/detail/T-Bar_Row_with_Handle_1.webp'), require('@/assets/exercises/detail/T-Bar_Row_with_Handle_2.webp')],
  },
  'Thigh_Abductor': {
    thumb: require('@/assets/exercises/thumb/Thigh_Abductor.webp'),
    frames: [require('@/assets/exercises/detail/Thigh_Abductor_1.webp'), require('@/assets/exercises/detail/Thigh_Abductor_2.webp')],
  },
  'Trail_Running_Walking': {
    thumb: require('@/assets/exercises/thumb/Trail_Running_Walking.webp'),
    frames: [require('@/assets/exercises/detail/Trail_Running_Walking_1.webp'), require('@/assets/exercises/detail/Trail_Running_Walking_2.webp')],
  },
  'Trap_Bar_Deadlift': {
    thumb: require('@/assets/exercises/thumb/Trap_Bar_Deadlift.webp'),
    frames: [require('@/assets/exercises/detail/Trap_Bar_Deadlift_1.webp'), require('@/assets/exercises/detail/Trap_Bar_Deadlift_2.webp')],
  },
  'Tricep_Dumbbell_Kickback': {
    thumb: require('@/assets/exercises/thumb/Tricep_Dumbbell_Kickback.webp'),
    frames: [require('@/assets/exercises/detail/Tricep_Dumbbell_Kickback_1.webp'), require('@/assets/exercises/detail/Tricep_Dumbbell_Kickback_2.webp')],
  },
  'Triceps_Pushdown': {
    thumb: require('@/assets/exercises/thumb/Triceps_Pushdown.webp'),
    frames: [require('@/assets/exercises/detail/Triceps_Pushdown_1.webp'), require('@/assets/exercises/detail/Triceps_Pushdown_2.webp')],
  },
  'Two-Arm_Dumbbell_Preacher_Curl': {
    thumb: require('@/assets/exercises/thumb/Two-Arm_Dumbbell_Preacher_Curl.webp'),
    frames: [require('@/assets/exercises/detail/Two-Arm_Dumbbell_Preacher_Curl_1.webp'), require('@/assets/exercises/detail/Two-Arm_Dumbbell_Preacher_Curl_2.webp')],
  },
  'Underhand_Cable_Pulldowns': {
    thumb: require('@/assets/exercises/thumb/Underhand_Cable_Pulldowns.webp'),
    frames: [require('@/assets/exercises/detail/Underhand_Cable_Pulldowns_1.webp'), require('@/assets/exercises/detail/Underhand_Cable_Pulldowns_2.webp')],
  },
  'Upright_Barbell_Row': {
    thumb: require('@/assets/exercises/thumb/Upright_Barbell_Row.webp'),
    frames: [require('@/assets/exercises/detail/Upright_Barbell_Row_1.webp'), require('@/assets/exercises/detail/Upright_Barbell_Row_2.webp')],
  },
  'Upright_Cable_Row': {
    thumb: require('@/assets/exercises/thumb/Upright_Cable_Row.webp'),
    frames: [require('@/assets/exercises/detail/Upright_Cable_Row_1.webp'), require('@/assets/exercises/detail/Upright_Cable_Row_2.webp')],
  },
  'Walking_Treadmill': {
    thumb: require('@/assets/exercises/thumb/Walking_Treadmill.webp'),
    frames: [require('@/assets/exercises/detail/Walking_Treadmill_1.webp'), require('@/assets/exercises/detail/Walking_Treadmill_2.webp')],
  },
  'Wide-Grip_Barbell_Bench_Press': {
    thumb: require('@/assets/exercises/thumb/Wide-Grip_Barbell_Bench_Press.webp'),
    frames: [require('@/assets/exercises/detail/Wide-Grip_Barbell_Bench_Press_1.webp'), require('@/assets/exercises/detail/Wide-Grip_Barbell_Bench_Press_2.webp')],
  },
  'Wide-Grip_Lat_Pulldown': {
    thumb: require('@/assets/exercises/thumb/Wide-Grip_Lat_Pulldown.webp'),
    frames: [require('@/assets/exercises/detail/Wide-Grip_Lat_Pulldown_1.webp'), require('@/assets/exercises/detail/Wide-Grip_Lat_Pulldown_2.webp')],
  },
  'Wide-Grip_Rear_Pull-Up': {
    thumb: require('@/assets/exercises/thumb/Wide-Grip_Rear_Pull-Up.webp'),
    frames: [require('@/assets/exercises/detail/Wide-Grip_Rear_Pull-Up_1.webp'), require('@/assets/exercises/detail/Wide-Grip_Rear_Pull-Up_2.webp')],
  },
  'Wrist_Roller': {
    thumb: require('@/assets/exercises/thumb/Wrist_Roller.webp'),
    frames: [require('@/assets/exercises/detail/Wrist_Roller_1.webp'), require('@/assets/exercises/detail/Wrist_Roller_2.webp')],
  },
  'Zercher_Squats': {
    thumb: require('@/assets/exercises/thumb/Zercher_Squats.webp'),
    frames: [require('@/assets/exercises/detail/Zercher_Squats_1.webp'), require('@/assets/exercises/detail/Zercher_Squats_2.webp')],
  },
};
