/**
 * Text matching for the exercise library.
 *
 * The library is named by free-exercise-db, so what a user types rarely equals
 * what a row is called: "pull down" vs "Wide-Grip Lat Pulldown", "RDL" vs
 * "Romanian Deadlift", "abs" vs "Crunches". Two mechanisms bridge that, and
 * both live here so the write side and the query side can never disagree.
 *
 * 1. Every source string is stored twice — spaced and with the spaces removed.
 *    A query token is matched as a substring, so "pull" and "down" each hit
 *    `widegriplatpulldown` and the single token "pulldown" hits it too. Word
 *    splitting stops mattering in either direction.
 * 2. Tags carry the vocabulary the name lacks (muscles, equipment, gym slang).
 *    They are generated by scripts/exercise-tags.mjs into the seed.
 */

type SearchSource = {
  name: string;
  tags?: string[] | null;
  primaryMuscles?: string[] | null;
  equipment?: string | null;
  category?: string | null;
};

export function normalize(value: string): string {
  return value
    .normalize('NFD')
    .replace(/\p{Diacritic}/gu, '')
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, ' ')
    .trim();
}

export function collapse(value: string): string {
  return normalize(value).replaceAll(' ', '');
}

/**
 * Tokens are stripped of everything but letters and digits, which also means a
 * query can never smuggle a `%` or `_` into the LIKE patterns built from it.
 */
export function searchTokens(query: string): string[] {
  const normalized = normalize(query);
  return normalized === '' ? [] : normalized.split(' ');
}

/**
 * The blob a search runs against. **The collapsed name comes first** — result
 * ranking in exercise-filters.ts reads a `LIKE 'query%'` on this column as
 * "the name starts with what was typed", which only holds while that stays true.
 */
export function buildSearchText(exercise: SearchSource): string {
  const parts = new Set<string>([collapse(exercise.name), normalize(exercise.name)]);

  for (const source of [
    ...(exercise.tags ?? []),
    ...(exercise.primaryMuscles ?? []),
    exercise.equipment,
    exercise.category,
  ]) {
    if (!source) continue;
    const normalized = normalize(source);
    if (normalized === '') continue;
    parts.add(normalized);
    parts.add(collapse(normalized));
  }

  return [...parts].join(' ');
}
