/**
 * emoji-datasource -> src/constants/emoji-data.ts
 *
 * The picker needs a flat, ordered list it can both section and search, so the
 * generated file is one array plus the section offsets into it. Skin-tone
 * variants are left out: a template cover carries a symbol, not a person.
 *
 * `obsoleted_by` is deliberately not filtered: it marks the gender-neutral forms
 * superseded by ZWJ sequences (🏋️ by 🏋️‍♂️), and those neutrals are the ones a
 * card cover usually wants.
 *
 * Run with `npm run build:emoji` after bumping emoji-datasource.
 */
import { writeFileSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

import data from 'emoji-datasource' with { type: 'json' };

const ROOT = resolve(dirname(fileURLToPath(import.meta.url)), '..');

/** Apple's own keyboard order. `Component` (bare skin tones) is not pickable. */
const SECTIONS = [
  ['Smileys & Emotion', '😀'],
  ['People & Body', '👋'],
  ['Animals & Nature', '🐻'],
  ['Food & Drink', '🍔'],
  ['Activities', '⚽️'],
  ['Travel & Places', '🚗'],
  ['Objects', '💡'],
  ['Symbols', '❤️'],
  ['Flags', '🏳️'],
];

const glyph = (unified) =>
  String.fromCodePoint(...unified.split('-').map((point) => parseInt(point, 16)));

const searchText = (entry) =>
  [...new Set([...entry.name.toLowerCase().split(/[^a-z0-9]+/), ...entry.short_names])]
    .filter(Boolean)
    .join(' ');

const rows = [];
const sections = [];

for (const [category, icon] of SECTIONS) {
  const start = rows.length;
  const own = data
    .filter((entry) => entry.category === category && entry.has_img_apple)
    .sort((a, b) => a.sort_order - b.sort_order);
  for (const entry of own) rows.push([glyph(entry.unified), searchText(entry)]);
  sections.push({ category, icon, start, count: rows.length - start });
}

const file = `// Generated by scripts/build-emoji.mjs — do not edit.
/** One emoji: the glyph, then the lowercase words it matches on. */
export type EmojiEntry = readonly [glyph: string, search: string];

export type EmojiSection = {
  readonly category: string;
  /** The glyph the category strip shows. */
  readonly icon: string;
  /** Offset into \`EMOJI\`, so sectioning and searching read the same array. */
  readonly start: number;
  readonly count: number;
};

export const EMOJI_SECTIONS: readonly EmojiSection[] = ${JSON.stringify(sections)};

export const EMOJI: readonly EmojiEntry[] = ${JSON.stringify(rows)};
`;

const out = resolve(ROOT, 'src/constants/emoji-data.ts');
writeFileSync(out, file);
console.log(`${rows.length} emoji in ${sections.length} sections -> ${out} (${Math.round(file.length / 1024)} KB)`);
