#!/usr/bin/env node
/**
 * Vendor clips → the stills the app bundles.
 *
 *   node scripts/build-images.mjs
 *
 * Input  the vendor clip's opening frame — the loop's `first` when it has one —
 *        colour corrected exactly like build-videos does it
 *
 * Output assets/exercises/poster/<slug>.webp   720x402  the detail sheet's still
 *        assets/exercises/thumb/<slug>.webp    150x150  centre-cropped, the list row
 *        src/lib/exercise-media-map.ts         the require map screens read
 *
 * The poster is what a row and a detail sheet draw before the clip has its
 * first frame, so it ships even though the clip ships beside it.
 *
 * Everything ships as lossy WebP q85 with a lossless alpha channel: ~half the
 * size of optimised PNG, natively decoded by expo-image, and unlike JPEG it
 * keeps transparency and does not smear crisp outlines.
 */
import { execFileSync } from 'node:child_process';
import { mkdirSync, readFileSync, statSync, writeFileSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';
import sharp from 'sharp';

import { colorFilter } from './exercise-grade.mjs';
import { METADATA_PATH, VIDEOS_DIR, groupOf } from './exercise-taxonomy.mjs';

const ROOT = resolve(dirname(fileURLToPath(import.meta.url)), '..');

const WEBP = { quality: 85, alphaQuality: 100, effort: 6 };
const SIZES = { thumb: 150 };

const warnings = [];
let bytes = 0;
let count = 0;

const write = (output, buf) => {
  mkdirSync(dirname(output), { recursive: true });
  writeFileSync(output, buf);
  bytes += buf.length;
  count++;
};

// --- Exercise stills -------------------------------------------------------
const meta = JSON.parse(readFileSync(resolve(ROOT, METADATA_PATH), 'utf8'));
const loops = JSON.parse(readFileSync(resolve(ROOT, 'scripts/exercise-loops.json'), 'utf8'));

// The poster sits under the clip until its first frame renders, so it is cut
// from that frame — a loop opens later than the vendor's own still, and every
// clip is regraded — rather than taken from the vendor's posters.
const openingFrame = (entry) => {
  const first = loops[entry.slug]?.first ?? 0;
  // rgb24 last: the grade runs at 16 bits, and a 16-bit PNG overflows execFileSync's buffer.
  const vf = [`select=eq(n\\,${first})`, 'scale=720:402:flags=lanczos', colorFilter(entry.slug), 'format=rgb24'];
  return execFileSync('ffmpeg', [
    '-loglevel', 'error', '-i', resolve(ROOT, VIDEOS_DIR, entry.videoFile),
    '-vf', vf.filter(Boolean).join(','),
    '-frames:v', '1', '-f', 'image2pipe', '-c:v', 'png', '-',
  ]);
};

for (const entry of meta) {
  // The generated map `require`s the clip, so a missing one fails Metro rather
  // than this script. Catch it here where the message says what to do.
  const clip = resolve(ROOT, `assets/exercise-videos/${groupOf(entry)}/${entry.slug}.mp4`);
  try {
    statSync(clip);
  } catch {
    warnings.push(`${entry.slug}: no clip — run \`npm run videos:pull\``);
  }

  const poster = await sharp(openingFrame(entry)).webp(WEBP).toBuffer();
  write(resolve(ROOT, `assets/exercises/poster/${entry.slug}.webp`), poster);

  // The row draws a 48pt circle. Cropping to a square here rather than letting
  // expo-image do it keeps a 720px frame out of every cell of a long list.
  const thumb = await sharp(poster)
    .resize(SIZES.thumb, SIZES.thumb, { fit: 'cover', position: 'centre' })
    .webp(WEBP)
    .toBuffer();
  write(resolve(ROOT, `assets/exercises/thumb/${entry.slug}.webp`), thumb);
}

writeExerciseMediaMap(meta);

console.log(`Wrote ${count} WebP files, ${(bytes / 1024 / 1024).toFixed(1)} MB total`);
if (warnings.length > 0) {
  console.warn(`\n${warnings.length} warning(s):`);
  for (const w of warnings) console.warn(`  - ${w}`);
}

/**
 * Metro only resolves static `require` literals, so the slug -> asset lookup
 * has to be written out. The clip requires are what pull the 412 mp4s into the
 * bundle, so a missing one is a Metro resolution error rather than a silently
 * still library.
 */
function writeExerciseMediaMap(entries) {
  const rows = [...entries]
    .sort((a, b) => a.slug.localeCompare(b.slug))
    .map((entry) =>
      [
        `  '${entry.slug}': {`,
        `    poster: require('@/assets/exercises/poster/${entry.slug}.webp'),`,
        `    thumb: require('@/assets/exercises/thumb/${entry.slug}.webp'),`,
        `    video: require('@/assets/exercise-videos/${groupOf(entry)}/${entry.slug}.mp4'),`,
        '  },',
      ].join('\n')
    );

  const file = `import type { ImageSource } from 'expo-image';

// Generated by scripts/build-images.mjs — do not edit.

export type ExerciseMedia = {
  poster: ImageSource;
  thumb: ImageSource;
  /** The bundled demo clip, as the asset module id \`require\` returns. */
  video: number;
};

export const EXERCISE_MEDIA: Record<string, ExerciseMedia> = {
${rows.join('\n')}
};
`;
  writeFileSync(resolve(ROOT, 'src/lib/exercise-media-map.ts'), file);
}
