#!/usr/bin/env node
/**
 * Vendor stills and mascot masters → the WebP the app bundles.
 *
 *   node scripts/build-images.mjs
 *
 * Input  assets/new_exercises_data/posters/<slug>.webp   720x402, the video's first frame
 *        assets/masters/mascot/<state>.png               1024x1024, PNG, alpha
 *
 * Output assets/exercises/poster/<slug>.webp   720x402  the detail sheet's still
 *        assets/exercises/thumb/<slug>.webp    150x150  centre-cropped, the list row
 *        src/lib/exercise-media-map.ts         the require map screens read
 *        assets/mascot/<state>.webp            512x512
 *
 * The poster is what a row and a detail sheet draw before the clip has its
 * first frame, so it ships even though the clip ships beside it.
 *
 * Everything ships as lossy WebP q85 with a lossless alpha channel: ~half the
 * size of optimised PNG, natively decoded by expo-image, and unlike JPEG it
 * keeps transparency and does not smear crisp outlines.
 */
import { mkdirSync, readdirSync, readFileSync, statSync, writeFileSync } from 'node:fs';
import { basename, dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';
import sharp from 'sharp';

import { METADATA_PATH, POSTERS_DIR, groupOf } from './exercise-taxonomy.mjs';

const ROOT = resolve(dirname(fileURLToPath(import.meta.url)), '..');

const WEBP = { quality: 85, alphaQuality: 100, effort: 6 };
const SIZES = { thumb: 150, mascot: 512 };
const MASCOT_MASTER = 1024;

const warnings = [];
let bytes = 0;
let count = 0;

const write = (output, buf) => {
  mkdirSync(dirname(output), { recursive: true });
  writeFileSync(output, buf);
  bytes += buf.length;
  count++;
};

// --- Exercise stills -------------------------------------------------------
const meta = JSON.parse(readFileSync(resolve(ROOT, METADATA_PATH), 'utf8'));

for (const entry of meta) {
  const src = resolve(ROOT, POSTERS_DIR, `${entry.slug}.webp`);
  try {
    statSync(src);
  } catch {
    warnings.push(`${entry.slug}: no poster at ${POSTERS_DIR}`);
    continue;
  }

  // The generated map `require`s the clip, so a missing one fails Metro rather
  // than this script. Catch it here where the message says what to do.
  const clip = resolve(ROOT, `assets/exercise-videos/${groupOf(entry)}/${entry.slug}.mp4`);
  try {
    statSync(clip);
  } catch {
    warnings.push(`${entry.slug}: no clip — run \`npm run videos:pull\``);
  }

  write(resolve(ROOT, `assets/exercises/poster/${entry.slug}.webp`), readFileSync(src));

  // The row draws a 48pt circle. Cropping to a square here rather than letting
  // expo-image do it keeps a 720px frame out of every cell of a long list.
  const thumb = await sharp(src)
    .resize(SIZES.thumb, SIZES.thumb, { fit: 'cover', position: 'centre' })
    .webp(WEBP)
    .toBuffer();
  write(resolve(ROOT, `assets/exercises/thumb/${entry.slug}.webp`), thumb);
}

writeExerciseMediaMap(meta);

// --- Mascot ----------------------------------------------------------------
const mascotMasters = resolve(ROOT, 'assets/masters/mascot');
const mascotFiles = (() => {
  try {
    return readdirSync(mascotMasters).filter((f) => f.toLowerCase().endsWith('.png')).sort();
  } catch {
    return [];
  }
})();

for (const file of mascotFiles) {
  const src = resolve(mascotMasters, file);
  const { width, height } = await sharp(src).metadata();
  if (width !== height) {
    warnings.push(`${file}: ${width}x${height} is not square`);
  } else if (width !== MASCOT_MASTER) {
    warnings.push(`${file}: ${width}px master, expected ${MASCOT_MASTER}px`);
  }
  const buf = await sharp(src)
    .resize(SIZES.mascot, SIZES.mascot, { fit: 'contain', background: { r: 0, g: 0, b: 0, alpha: 0 } })
    .webp(WEBP)
    .toBuffer();
  write(resolve(ROOT, `assets/mascot/${basename(file, '.png')}.webp`), buf);
}

console.log(`Wrote ${count} WebP files, ${(bytes / 1024 / 1024).toFixed(1)} MB total`);
if (warnings.length > 0) {
  console.warn(`\n${warnings.length} warning(s):`);
  for (const w of warnings) console.warn(`  - ${w}`);
}

/**
 * Metro only resolves static `require` literals, so the slug -> asset lookup
 * has to be written out. The clip requires are what pull the 412 mp4s into the
 * bundle, so a missing one is a Metro resolution error rather than a silently
 * still library.
 */
function writeExerciseMediaMap(entries) {
  const rows = [...entries]
    .sort((a, b) => a.slug.localeCompare(b.slug))
    .map((entry) =>
      [
        `  '${entry.slug}': {`,
        `    poster: require('@/assets/exercises/poster/${entry.slug}.webp'),`,
        `    thumb: require('@/assets/exercises/thumb/${entry.slug}.webp'),`,
        `    video: require('@/assets/exercise-videos/${groupOf(entry)}/${entry.slug}.mp4'),`,
        '  },',
      ].join('\n')
    );

  const file = `import type { ImageSource } from 'expo-image';

// Generated by scripts/build-images.mjs — do not edit.

export type ExerciseMedia = {
  poster: ImageSource;
  thumb: ImageSource;
  /** The bundled demo clip, as the asset module id \`require\` returns. */
  video: number;
};

export const EXERCISE_MEDIA: Record<string, ExerciseMedia> = {
${rows.join('\n')}
};
`;
  writeFileSync(resolve(ROOT, 'src/lib/exercise-media-map.ts'), file);
}
